---
title: "Matrix Decompositions"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 4
      primary: '#22B455'
      bg: '#020204'
      fg: '#92E5A1'
      base_font:
        google: IBM Plex Sans
    css: www/custom.css
editor_options:
  chunk_output_type: console
runtime: shiny
resource_files:
- www/custom.css
- www/matrix.jpg
- www/matrix.regular.ttf
- www/matrix.ttf
- www/wp.png
- rmd/cholesky.Rmd
- rmd/eigen.Rmd
- rmd/lu.Rmd
- rmd/qr.Rmd
- rmd/svd.Rmd
---

```{r global, include=FALSE}
# webshot2::webshot("http://127.0.0.1:6095/app.Rmd", file = "screenshot.png", delay = 10)
library(tidyverse)
library(shiny)
library(here)
library(markdown)
source(here::here("helpers.R"))
```

<style>
.irs-grid-pol.small {
  height: 0px;
}

.form-group {
  margin-bottom: 0.5rem;
  margin-top:    0.5rem;
}

body,
.dashboard-page-wrapper,
#section-controls,
#section-section {
  background: #020204;
}

#section-controls,
.chart-wrapper {
  border: none;
}
</style>

Controls { .sidebar data-width=300 }
-----------------------------------------------------------------------


```{r inputs}
withMathJax()

radioButtons(
  "decomposition",
  tags$strong("Decomposition"),
  choices = list(
    "SVD" = "svd",
    "Eigen"  = "eigen",
    "\\(QR\\)" = "qr",
    "\\(LU\\)" = "lu",
    "Cholesky" = "cholesky"
  )
)

textAreaInput(
  "matrix",
  label = tags$strong("Matrix values"),
  rows = 4,
  # value = "1, 2,3,\n2, 4.5, 6,\n3, 3, 3"
  value = "4, 12, -16, 12, 37, -43, -16, -43, 98"
  # value = "1, 2\n2, 1"
)

sliderInput(
  "nrows",
  label = tags$strong("Number of rows and cols"),
  min = 2,
  max = 5,
  value = 3
)

htmlOutput("matrix_render")
```

<br/>

<small>
```{r}
htmltools::includeMarkdown("readme.md")
```
</small>

```{r, context="server"}
# bslib::bs_themer()
```


Row 
-----------------------------------------------------------------------

###

```{r}
htmlOutput("decomposition_output")
```

```{r, context="server"}
vector <- reactive({
  
  vector <- input$matrix |> 
    str_split("\\,") |> 
    unlist() |> 
    as.numeric()
  
  vector
  
})

matrixA <- reactive({
  
  vector <- vector()
  
  matrixA <- matrix(
    vector, 
    nrow = input$nrows, 
    ncol = input$nrows, 
    byrow = TRUE
    )
  
  matrixA
  
})

output$matrix_render <- renderUI({
  
  vector  <- vector()
  matrixA <- matrixA()
  
  warning_msg <- NULL
  
  if(length(vector)%%input$nrows != 0) {
    
    warning_msg <- str_glue(
      "Data length {length(vector)} is not a sub-multiple or multiple of the number of rows {input$nrows}. Recycling vector elements."
    )

  } else if ( length(vector) < input$nrows**2 ) {
    
    warning_msg <- str_glue(
      "Only first {input$nrows**2} given values will be used."
    )
    
  }
  
  tagList(
    withMathJax(),
    str_c("$$ A = ", matrix2latex(matrixA), "$$"),
    if(!is.null(warning_msg)) tags$small(tags$i(class = "text-warning", warning_msg))
  )
  
})  

output$decomposition_output <- renderUI({
  
  matrixA <- matrixA()
  
  file <- here(str_c("rmd/", input$decomposition, ".Rmd"))
  
  withMathJax(
    HTML(
      readLines(
        rmarkdown::render(
          input = file,
          output_format = "html_fragment",
          output_file = "temp.html",
          quiet = TRUE,
          params = list(mat = matrixA)
          ),
        encoding = "UTF-8"
        )
      )
    )
  
  
})
```

