---
title: "K-means"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 4
      primary: '#262162'
      navbar-bg: '#262162'
      base_font:
        google: IBM Plex Sans
runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r global, include=FALSE}
library(shiny)
library(shinyWidgets)
library(tidyverse)
library(markdown)

primary_color <- "#262162"

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

<style>
.irs-grid-pol.small {
  height: 0px;
}

.form-group {
  margin-bottom: 0.5rem;
  margin-top:    0.5rem;
}

.sidebar {
  padding-top: 1rem;
}

</style>

Controls { .sidebar data-width=300 }
-----------------------------------------------------------------------

```{r inputs}
shiny::sliderInput(
  "n_groups",
  tags$span("Number of groups to simulate"),
  value = 3,
  min = 1,
  max = 10
)

shiny::sliderInput(
  "n",
  tags$span("Number of points to simulate"),
  value = 300,
  min = 100,
  max = 500,
  step = 100
)

shiny::sliderInput(
  "k",
  tags$span("Parameter \\(k\\) for \\(K\\)-Means"),
  value = 4,
  min = 2,
  max = 10
)

shinyWidgets::sliderTextInput(
  "iter",
  tags$span("Iterations of algorithm"),
  choices = 0:15,
  selected = 4,
  grid = TRUE,
  # step = 1,
  # min = 0,
  # max = 15,
  # animate = TRUE,
  animate = animationOptions(interval = 2000)
)
```

<hr/>

<small>
```{r}
htmltools::includeMarkdown("readme.md")
```
</small>


```{r reactives, context="server"}
# input <- list(
#   n_groups = 4,
#   n = 150,
#   k = 3,
#   iter = 2
#   ); input

# input <- list(
#   n_groups = 3,
#   n = 500,
#   k = 5,
#   iter = 2
#   ); input

data <- reactive({

  set.seed(123)
  
  data <- klassets::sim_groups(n = input$n, groups = input$n_groups)
  
  data

})

# k means iterations all
kmi_all <- reactive({
  
  data <- data()
  
  ks <- 1:10
  
  kmi_all <- map(ks, ~ klassets::kmeans_iterations(df = data, centers = .x))
  
  kmi_all
  
})

# k means iteration (for actual selected k)
kmi <- reactive({
  
  kmi_all <- kmi_all()
  
  kmi <- kmi_all[[input$k]]
  
  # updateSliderInput
  updateSliderTextInput(
    session = getDefaultReactiveDomain(),
    inputId = "iter",
    choices = 1:max(kmi$centers$iteration),
    selected = sample(1:max(kmi$center$iteration), size = 1)
    )
  
  kmi
  
})

kmi_plot <- reactive({
  
  kmi <- kmi()
  
  k <- input$k
  
  kmi_plot <- plot(kmi)
  
  kmi_plot

})

data_elbow <- reactive({
  
  kmi_all <- kmi_all()
  
  ks <- 1:10
  
  data_hist_all <- kmi_all |> 
    map(pluck, "points") |> 
    # map(filter, iteration == max(iteration)) |> 
    # map(select, -iteration, -id) |> 
    map2_df(ks, ~ mutate(.x, k = .y, .before = 1))
  
  data_hist_all <- data_hist_all |> 
    # filter(k == 2) |> 
    # distance from cluster
    group_by(k, iteration, cluster) |> 
    mutate(xc = mean(x), yc = mean(y)) |> 
    mutate(dc = (x - xc)^2 + (y - yc)^2) |> 
    # distance from total center
    ungroup() |> 
    group_by(k, iteration) |> 
    mutate(xt = mean(x), yt = mean(y)) |> 
    mutate(dt = (x - xt)^2 + (y - yt)^2) |> 
    ungroup()
  
  data_elbow <- data_hist_all |> 
    group_by(k, iteration) |> 
    summarise(dc = sum(dc), dt = sum(dt)) |> 
    mutate(wc = 1 - dc/dt) |> 
    ungroup()
  
  data_elbow
  
})


```

Row {data-height=500}
-----------------------------------------------------------------------

### 

```{r}
plotOutput("iter_plot", width = "100%", height = "100%")
```

```{r, context="server"}
output$iter_plot <- renderPlot({
# output$iter_plot <- renderCachedPlot({

  kmi_plot <- kmi_plot()
  
  kmi_plot +
    ggforce::facet_wrap_paginate(
      vars(iteration),
      nrow = 1,
      ncol = 1,
      page = input$iter + 0
      )

})
# }, cacheKeyExpr = { list(input$n_groups, input$n, input$k, input$iter)})
```


Row
-----------------------------------------------------------------------

### 

```{r}
plotOutput("elbow", width = "100%", height = "100%")
```

```{r, context="server"}
output$elbow <- renderPlot({
  
  data_elbow <- data_elbow()
  
  daux <- data_elbow |> 
    group_by(k) |> 
    filter(iteration == max(iteration)) |> 
    ungroup()
  
  ggplot(daux, aes(k, 1 - wc)) +
    geom_line(size = 1.2, color = "gray60") +
    # kunstomverse::geom_point2
    geom_point(
      data = filter(daux, k == input$k),
      shape = 21, 
      size = 5,
      color = "white", 
      fill = primary_color
      ) +
    scale_x_continuous(breaks = 1:10, minor_breaks = NULL)
  
})
```

### 

```{r}
plotOutput("convergence", width = "100%", height = "100%")
```

```{r, context="server"}
output$convergence <- renderPlot({
  
  data_elbow <- data_elbow()
  
  daux <- data_elbow |> 
    filter(k == input$k, iteration > 0) |> 
    ungroup()
  
  ggplot(daux, aes(iteration, 1 - wc)) +
     geom_line(size = 1.2, color = "gray60") +
     geom_point(
      data = filter(daux, iteration == input$iter),
      shape = 21, 
      size = 5,
      color = "white", 
      fill = primary_color
      ) +
    scale_x_continuous(breaks = daux$iteration, minor_breaks = NULL)

})
```


