---
title: "Google Analytics & Highcharter"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    favicon: https://www.iconexperience.com/_img/o_collection_png/office/24x24/plain/chart_line.png
    css: styles.css
    orientation: rows
    vertical_layout: fill
    social: menu
    source_code: embed
    theme: lumen
---

```{r setup, include=FALSE}
# rm(list = ls())
knitr::opts_chunk$set(echo = FALSE)
library("flexdashboard")
library("rga")
library("htmltools")
library("dplyr")
library("tidyr")
library("purrr")
library("stringr")
library("lubridate")
library("scales")
library("highcharter")
library("DT")
library("viridis")

# rga.open(instance = "ga")
# saveRDS(ga, "ga.rds")
#### pars ####
ga <- readRDS("ga.rds")
maincolor <- "#000080"
colorsscale <- inferno(10)
ID <- "113913503"

options(highcharter.theme = hc_theme_smpl(colors = list(maincolor)))

options(DT.options = list(info = FALSE, searching = FALSE, 
                          paging = FALSE, pageLength = 100000,
                          ordering = TRUE, lengthChange = FALSE))

# input <- list(daterange = daterange <- c(Sys.Date() - 31, Sys.Date() - 1),
#               metric = metric <- "sessions",
#               timedim = timedim <- "date")

get_metric_num <- function(metric = "sessions", daterange, formatfun = comma) {
  ga$getData(ID, start.date = daterange[1], end.date = daterange[2],
             metrics = paste0("ga:", metric), dimensions = "") %>% 
    as.numeric() %>% 
    round(2) %>% 
    formatfun
}

get_metric_hc <- function(metric = "sessions", daterange, timedim) {
  
  todatetimefun <- switch(timedim,
    date = identity,
    dateHour = ymd_h,
    yearWeek = function(x) x %>% paste(1) %>% as.Date(format = "%Y%U %u"),
    yearMonth = function(x) x %>% paste0("01") %>% ymd()
  )
  
  ga$getData(ID, start.date = daterange[1], end.date = daterange[2],
             metrics = paste0("ga:", metric), dimensions = paste0("ga:", timedim)) %>% 
    tbl_df() %>% 
    setNames(c("x", "y")) %>% 
    mutate(x = todatetimefun(x)) %>% 
    mutate(x = datetime_to_timestamp(x)) %>% 
    hc_add_series_df(highchart(), ., name = metric) %>% 
    hc_xAxis(type = "datetime") %>% 
    hc_legend(enabled = FALSE) %>% 
    hc_chart(
      type = "area",
      cursor = "pointer",
      events = list(
        click = JS("function(){
                  console.log(this.series[0].name);
                  Shiny.onInputChange('metric', this.series[0].name);
                  }")
        )
      ) %>% 
    hc_plotOptions(
      series = list(
        cursor = "pointer",
        marker = list(enabled = FALSE),
        states = list(hover = list(enabled = FALSE)),
        events = list(
          click = JS("function(){
                     console.log(this.name);
                     Shiny.onInputChange('metric', this.name);
                     }")
          )
        )
      )
}

seconds_to_min <- function(x) {
  td <- seconds_to_period(round(x))
  sprintf("%d:%02d:%02d", td@hour, minute(td), second(td)) 
}

percent2 <- function(x){ {x/100} %>% percent }

get_valueBox <- function(metric = "sessions", daterange, timedim, icon = "fa-user", formatfun = comma) {
  hcspakr <- get_metric_hc(metric, daterange, timedim = timedim) %>%
    hc_add_theme(hc_theme_sparkline(colors = list("white"), tooltip = list(enabled = FALSE)))
  hcspakr$height <- 30
  valueBox(
    tagList(
      get_metric_num(metric, daterange, formatfun = formatfun),
      hcspakr
      ),
    icon = icon,
    color = "navy")
}

aggfun <- reactive({

  ifelse(input$metric %in% c("sessions", "users"), sum, median)

})

orddir <- reactive({
  ifelse(input$metric %in% c("bounceRate"), -1, 1)
})

```

Sidebar {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("period", label = "Period",  selected = "month",
            choices = c("Yesterday" = "yesterday", "Today" = "today",
                        "Past 7 days" = "week", "Past Month" = "month",
                        "Year to date" = "ytd"))

dateRangeInput("daterange", label = "Date Range", start = Sys.Date() - 31,
               end = Sys.Date() - 1, min = ga$getFirstDate(ID), max = Sys.Date())

selectInput("metric", label = "Metric", selected = "sessions",
            choices = c("sessions", "users", "pageviews", "pageviewsPerSession",
                        "avgSessionDuration", "bounceRate", "percentNewSessions"))

selectInput("timedim", label = "Time", selected = "date",
            choices = c("Day" = "date", "Weekly" = "yearWeek", "Month" = "yearMonth"))

observeEvent(input$period, {
  
  vals <- switch(input$period,
    yesterday = Sys.Date() - c(1, 1),
    today = Sys.Date() - c(0, 0),
    week = Sys.Date() - c(7, 1),
    month = Sys.Date() - c(31, 1),
    ytd = c(format(Sys.Date(), "%Y-01-01"), as.character(Sys.Date()))
  )
  
  updateDateRangeInput(session, "daterange", start = vals[1], end = vals[2])
  
})
```

Row
-----------------------------------------------------------------------

### Sessions  {.value-box}
```{r}
renderValueBox({get_valueBox("sessions", input$daterange, input$timedim, "fa-user")})
```

### Users {.value-box}
```{r}
renderValueBox({get_valueBox("users", input$daterange, input$timedim, "fa-users")})
```

### Page Views {.value-box}
```{r}
renderValueBox({get_valueBox("pageviews", input$daterange, input$timedim, "fa-eye")})
```


### Pages per Session {.value-box}
```{r}
renderValueBox({get_valueBox("pageviewsPerSession", input$daterange, input$timedim, "fa-eye")})
```

### Avg Duration of Sessions {.value-box}
```{r}
renderValueBox({
  get_valueBox("avgSessionDuration", input$daterange, input$timedim, "fa-clock-o", formatfun = seconds_to_min)
  })
```

### Bounce Rate {.value-box}
```{r}
renderValueBox({
  get_valueBox("bounceRate", input$daterange, input$timedim, "fa-sign-out", formatfun = percent2)
  })
```

### Percent New Sessions {.value-box}
```{r}
renderValueBox({
  get_valueBox("percentNewSessions", input$daterange, input$timedim, "fa-plus", formatfun = percent2)
  })
```


Row {data-height=200}
-----------------------------------------------------------------------
### Detailed View 
```{r}
renderHighchart({
  get_metric_hc(input$metric, input$daterange, input$timedim) %>%
    hc_yAxis(showLastLabel = FALSE, showFirstLabel = FALSE) %>% 
    hc_plotOptions(series = list(fillOpacity = 0.1))
})
```

Row {.tabset .tabset-fade data-height=350}
-----------------------------------------------------------------------
### Referral Path
```{r}
renderDataTable({
  
  mtrcs <- c("sessions", "percentNewSessions", "users",
             "bounceRate",  "pageviewsPerSession", "avgSessionDuration")
  mtrcs <- paste0("ga:", mtrcs, collapse = ",")
  
  dfref <- ga$getData(ID, start.date = input$daterange[1], end.date = input$daterange[2],
                      metrics = mtrcs,
                      dimensions = "ga:source,ga:referralPath",
                      filters = "ga:medium==referral") %>% 
    tbl_df() %>% 
    unite(url, source, referralPath, sep = "") %>% 
    # mutate(url = substr(url, 0, nchr),
    #        url = ifelse(nchar(url) == nchr, paste0(url, "..."), url)) %>% 
    arrange(desc(sessions)) %>% 
    rename(percNewSess = percentNewSessions,
           pagVwsPSess = pageviewsPerSession,
           avgSessDur = avgSessionDuration) %>% 
    map_if(is.numeric, round) %>% 
    as_data_frame()
  
  datatable(dfref, rownames = FALSE,
            extensions = c("TableTools"),
            options = list(scrollY = 350))
  
})
```

### Referral Source
```{r}
renderHighchart({
  
  ncum <- 10
  nses <- 5
  
  summfun <- aggfun()
  ordrdir <- orddir()
  
  dfref <- ga$getData(ID, start.date = input$daterange[1], end.date = input$daterange[2],
                      metrics = paste0("ga:sessions,ga:", input$metric),
                      dimensions = "ga:source",
                      filters = "ga:medium==referral") %>% 
    setNames(c("source", "sessionsaux", "metric")) %>% 
    tbl_df() %>% 
    mutate(source = ifelse(sessionsaux < nses, "others", source)) %>% 
    group_by(source) %>% 
    summarise(metric = summfun(as.numeric(metric)), sessionsaux = sum(as.numeric(sessionsaux))) %>% 
    ungroup() %>% 
    arrange(desc(ordrdir * metric)) %>% 
    mutate(source = ifelse(row_number() > ncum, "others", source)) %>% 
    group_by(source) %>% 
    summarise(metric = summfun(as.numeric(metric)), sessionsaux = sum(as.numeric(sessionsaux))) %>%  
    ungroup() %>% 
    arrange(desc(ordrdir * metric))
  
  highchart() %>% 
    hc_chart(type = "bar") %>% 
    hc_add_series(data = dfref$metric, name = input$metric) %>% 
    hc_xAxis(categories = dfref$source)

})
```

### dayOfWeek vs hour
```{r}
renderHighchart({
  m <- ga$getData(ID, start.date = input$daterange[1], end.date = input$daterange[2],
             metrics = paste0("ga:", input$metric), dimensions = "ga:dayOfWeek,ga:hour") %>% 
    tbl_df() %>% 
    setNames(c("dayOfWeek", "hour", "metric")) %>%
    map_if(is.factor, as.character) %>% 
    as_data_frame() %>% 
    complete(dayOfWeek = as.character(0:6), hour = as.character(0:23)) %>% 
    mutate(metric = ifelse(is.na(metric), 0, metric),
           hour = as.numeric(hour)) %>% 
    arrange(dayOfWeek, hour) %>% 
    spread(hour, metric) %>% 
    select(-1) %>% 
    as.matrix() 
  
  rownames(m) <- getOption("highcharter.lang")$weekdays
  colnames(m) <- paste0(colnames(m), ":00")

  hchart(m, name = input$metric) %>% 
    hc_yAxis(reversed = TRUE, title = list(text = "")) %>% 
    hc_colorAxis(stops = color_stops(colors = colorsscale))
    
})
```



### Pages
```{r}
renderHighchart({
  
  ncum <- 14
  
  summfun <- aggfun()
  ordrdir <- orddir()
  
  dfref <- ga$getData(ID, start.date = input$daterange[1], end.date = input$daterange[2],
                      metrics = paste0("ga:", input$metric),
                      dimensions = "ga:pagePath") %>% 
    tbl_df() %>% 
    setNames(c("pagePath", "metric")) %>% 
    arrange(desc(ordrdir * metric)) %>% 
    mutate(pagePath = ifelse(row_number() > ncum, "others", pagePath)) %>% 
    group_by(pagePath) %>% 
    summarise(metric = summfun(as.numeric(metric))) %>%  
    ungroup() %>% 
    arrange(desc(ordrdir * metric))
    
  highchart() %>% 
    hc_chart(type = "bar") %>% 
    hc_add_series(data = dfref$metric, name = input$metric) %>% 
    hc_xAxis(categories = dfref$pagePath)

})
```


### Channels
```{r}
renderHighchart({
  
  summfun <- aggfun()
  ordrdir <- orddir()
  
  dfref <- ga$getData(ID, start.date = input$daterange[1], end.date = input$daterange[2],
                      metrics = paste0("ga:", input$metric),
                      dimensions = "ga:channelGrouping") %>% 
    tbl_df() %>% 
    setNames(c("channelGrouping", "metric")) %>% 
    arrange(desc(ordrdir * metric))
  
  highchart() %>% 
    hc_chart(type = "column") %>% 
    hc_add_series(data = dfref$metric, name = input$metric) %>% 
    hc_xAxis(categories = dfref$channelGrouping)

})
```

### Input (Internal)
```{r}
renderPrint({reactiveValuesToList(input)})
```




